### ISSUE TITLE
Site improvements

### ISSUE THREAD

**Issue by continentaldivide** [continentaldivide/marinaragospel.com#1]
## Todo

- [x] Add some explicit reference to suggestions@marinaragospel.com
- [x] Add additional quotes
- [x] Implement code to prevent random from grabbing the same quote that's currently displayed
- [ ] Fine-tune page colors
- [ ] Create and implement favicon
- [ ] Buy milk
